sudo: required
services:
  - docker

before_install:
  - docker build -t teemutt/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run teemutt/react-test npm test -- --coverage

after_success:
  - docker build -t  teemutt/multi-client ./client
  - docker build -t  teemutt/multi-nginx ./nginx
  - docker build -t  teemutt/multi-server ./server
  - docker build -t  teemutt/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push teemutt/multi-client
  - docker push teemutt/multi-nginx
  - docker push teemutt/multi-server
  - docker push teemutt/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-347583411394
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY